app/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from main.views import IndexPageView

urlpatterns = [
    url('i18n/', include('django.conf.urls.i18n')),
    url(r'^stocks/', include('stocks.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexPageView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        url(r'__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

portfolio/urls.py
from django.conf.urls import url

from portfolio.views import portfolio_designer, portfolio, orders, dividend


app_name = 'portfolio'

urlpatterns = [
    url(r'^view/(?P<id>\d+)[/]*$', portfolio.portfolio_viewer, name='portfolio_viewer'),
    url(r'^list[/]*$', portfolio.portfolio_list, name='portfolio_list'),
    url(r'^designer[/]*$', portfolio_designer.portfolio_designer, name='portfolio_designer'),
    url(r'^save/', portfolio_designer.save_portfolio, name='save_portfolio'),
    url(r'^order/delete/(?P<pk>\d+)/', orders.OrderDeleteView.as_view(), name='order_delete_view'),
    url(r'^order/add/', orders.OrderCreateView.as_view(), name='order_create_view'),
    url(r'^order/buy/(?P<portfolio_id>\d+)/', orders.OrderCreateView.as_view(), name='buy'),
    url(r'^order/sell/(?P<portfolio_id>\d+)/(?P<stock_id>\d+)/', orders.OrderCreateView.as_view(), name='sell'),
    url(r'^dividend/add/(?P<portfolio_id>\d+)/(?P<stock_id>\d+)/', dividend.DividendCreateView.as_view(), name='dividend'),
    url(r'^dividend/edit/(?P<pk>\d+)/', dividend.DividendEditView.as_view(), name='div_edit'),
    url(r'^dividend/delete/(?P<pk>\d+)/', dividend.DividendDeleteView.as_view(), name='div_delete'),
    url(r'^order/edit/(?P<pk>\d+)/', orders.OrderUpdateView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/', portfolio.PortfolioDeleteView.as_view(), name='portfolio_delete_view')
]

stocks/urls.py
from django.conf.urls import url

from stocks.views import strategy, orders
from stocks.views import misc

app_name = 'stocks'

urlpatterns = [
    url(r'^index[/]*$', misc.stock_list_index, name='stock_list_index'),
    url(r'^region[/]*$', misc.stock_list_region, name='stock_list_region'),
    url(r'^signals[/]*$', misc.stock_signal, name='stock_signal'),
    url(r'^signal/view/(?P<signal_id>\d+)[/]*$',
        misc.stock_signal_viewer_id, name='stock_signal_viewer_id'),
    url(r'^portfolio/(?P<id>\w+)[/]*$',
        strategy.strategy_viewer, name='portfolio_viewer'),
    url(r'^signals/performance[/]*$', misc.stock_signal_performance,
        name='stock_signal_performance'),
    url(r'^signals/today[/]*$', misc.stock_signal_today,
        name='stock_signal_today'),
    url(r'^(?P<stock_id>[\d]+)[/]*$', misc.stock_data, name='stock_data'),
    url(r'^filter/stock_is_hot[/]*$', misc.stock_list_filter_stock_is_hot,
        name='stock_list_filter_stock_is_hot'),
    url(r'^filter/piotroski[/]*$', misc.stock_list_filter_piotroski,
        name='stock_list_filter_piotroski'),
    url(r'^filter/levermann[/]*$', misc.stock_list_filter_levermann,
        name='stock_list_filter_levermann'),
    url(r'^filter[/]*$', misc.stock_list_filter,
        name='stock_list_filter'),
    url(r'^strategies[/]*$', strategy.strategy_list, name='strategies'),
    url(r'^strategy/view/(?P<id>\w+)[/]*$', strategy.strategy_viewer, name='strategy_view'),
    url(r'^order/view/(?P<order_id>\d+)[/]*$',
        misc.order_view, name='order_viewer_id'),
    url(r'^order/delete/(?P<pk>\d+)/', orders.OrderDeleteView.as_view(), name='order_delete_view'),
    url(r'^order/add/', orders.OrderCreateView.as_view(), name='order_create_view'),
    url(r'^strategy/delete/(?P<pk>\d+)/', strategy.StrategyDeleteView.as_view(), name='strategy_delete_view'),
]

portfolio/forms/div_form.py
from bootstrap_modal_forms.forms import BSModalForm

from portfolio.models import Dividend
from tempus_dominus.widgets import DatePicker
from django.forms import DateTimeField, FloatField, NumberInput


class DivForm(BSModalForm):

    date = DateTimeField(
        widget=DatePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        )
    )
    sum = FloatField(required=True,  min_value=0, widget=NumberInput(attrs={'type': 'number', 'step': "0.01"}))

    def __init__(self, *args, **kwargs):
        self.stock_id = kwargs.pop('stock_id')
        self.portfolio_id = kwargs.pop('portfolio_id')
        super(DivForm, self).__init__(*args, **kwargs)
        self.fields['sum'].required = True
        self.fields['date'].required = True

    def clean(self):
        self.instance.portfolio_id = self.portfolio_id
        self.instance.stock_id = self.stock_id
        return super(DivForm, self).clean()

    class Meta:
        model = Dividend
        exclude = ['stock', 'portfolio']

portfolio/forms/div_form_update.py
from bootstrap_modal_forms.forms import BSModalForm
from bootstrap_modal_forms.mixins import CreateUpdateAjaxMixin

from portfolio.models import Dividend
from tempus_dominus.widgets import DatePicker
from django.forms import DateTimeField


class DivFormUpdate(BSModalForm):

    date = DateTimeField(
        widget=DatePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        )
    )

    def __init__(self, *args, **kwargs):
        super(DivFormUpdate, self).__init__(*args, **kwargs)
        self.fields['sum'].required = True
        self.fields['date'].required = True

    class Meta:
        model = Dividend
        fields = ['stock', 'sum', 'date']

    def save(self):
        my_div = super(CreateUpdateAjaxMixin, self).save()
        return my_div

portfolio/forms/order_form_update.py
from bootstrap_modal_forms.forms import BSModalForm
from bootstrap_modal_forms.mixins import CreateUpdateAjaxMixin

from portfolio.models import Orders
from tempus_dominus.widgets import DateTimePicker
from django.forms import DateTimeField, DecimalField


class OrderFormUpdate(BSModalForm):

    date = DateTimeField(
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        )
    )
    commission = DecimalField(required=False, max_digits=6, min_value=0)
    price = DecimalField(required=False, min_value=0)

    def __init__(self, *args, **kwargs):
        super(OrderFormUpdate, self).__init__(*args, **kwargs)
        self.fields['price'].required = True
        self.fields['commission'].required = True
        self.fields['size'].required = True
        self.fields['date'].required = True

    class Meta:
        model = Orders
        fields = ['stock', 'date', 'size', 'price', 'commission']

    def save(self):
        my_order = super(CreateUpdateAjaxMixin, self).save()
        return my_order

portfolio/views/dividend.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from portfolio.forms.div_form import DivForm
from portfolio.forms.div_form_update import DivFormUpdate
from portfolio.models import Portfolio, Dividend

from stocks.models import Stock


class DividendDeleteView(BSModalDeleteView):
    model = Dividend
    fields = '__all__'
    template_name = 'delete.html'
    success_message = 'Success: Dividend was deleted.'

    def get_success_url(self):
        portfolio = self.object.portfolio.id
        return reverse_lazy('portfolio:portfolio_viewer', kwargs={'id': portfolio})


class DividendEditView(BSModalUpdateView):
    template_name = 'post.html'
    form_class = DivFormUpdate
    success_message = 'Success: Dividend was updated.'
    dividend = None
    portfolio = None
    model = Dividend

    def dispatch(self, request, *args, **kwargs):
        self.dividend = get_object_or_404(Dividend, id=kwargs['pk'])
        self.portfolio = get_object_or_404(Portfolio, id=self.dividend.portfolio_id, user=request.user)
        return super(DividendEditView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DividendEditView, self).get_context_data(**kwargs)
        context['headline'] = 'Update dividend {}'.format(self.dividend.id)
        context['btn_txt'] = 'Save'
        return context


class DividendCreateView(BSModalCreateView):
    portfolio = None
    stock = None
    template_name = 'post.html'
    form_class = DivForm
    dividend = None

    def dispatch(self, request, *args, **kwargs):
        self.portfolio = get_object_or_404(Portfolio, id=kwargs['portfolio_id'], user=request.user)
        self.stock = get_object_or_404(Stock, id=kwargs['stock_id'])
        return super(DividendCreateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DividendCreateView, self).get_context_data(**kwargs)
        context['headline'] = 'Add dividends for {} ({})'.format(self.stock.symbol, self.stock.name)
        context['btn_txt'] = 'Add'
        return context

    def get_form_kwargs(self):
        kwargs = super(DividendCreateView, self).get_form_kwargs()
        kwargs['stock_id'] = self.stock.id
        kwargs['portfolio_id'] = self.portfolio.id
        return kwargs

    def get_success_url(self):
        return reverse_lazy('portfolio:portfolio_viewer', kwargs={'id': self.portfolio.id})

portfolio/views/orders.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse

from portfolio.forms.order_form import OrderForm
from portfolio.forms.order_form_update import OrderFormUpdate
from portfolio.models import Portfolio, Orders

from stocks.models import Stock


class OrderDeleteView(BSModalDeleteView):
    model = Orders
    fields = '__all__'
    success_message = 'Success: Order was deleted.'
    template_name = 'delete.html'

    def get_success_url(self):
        portfolio = self.object.portfolio.id
        return reverse_lazy('portfolio:portfolio_viewer', kwargs={'id': portfolio})


class OrderUpdateView(BSModalUpdateView):
    template_name = 'post.html'
    form_class = OrderFormUpdate
    success_message = 'Success: Order was updated.'
    order = None
    portfolio = None
    model = Orders

    def dispatch(self, request, *args, **kwargs):
        self.order = get_object_or_404(Orders, id=kwargs['pk'])
        self.portfolio = get_object_or_404(Portfolio, id=self.order.portfolio_id, user=request.user)
        return super(OrderUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)
        context['headline'] = 'Update order {}'.format(self.order.id)
        context['btn_txt'] = 'Save'
        return context


class OrderCreateView(BSModalCreateView):
    portfolio = None
    stock = None
    is_sell = True
    template_name = 'post.html'
    form_class = OrderForm

    def dispatch(self, request, *args, **kwargs):
        self.portfolio = get_object_or_404(Portfolio, id=kwargs['portfolio_id'], user=request.user)
        self.is_sell = '/sell/' in request.path
        self.stock = None
        if self.is_sell:
            self.stock = get_object_or_404(Stock, id=kwargs['stock_id'])
        return super(OrderCreateView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(OrderCreateView, self).get_form_kwargs()
        kwargs['sell'] = self.is_sell
        kwargs['stock_id'] = None if self.stock is None else self.stock.id
        kwargs['portfolio_id'] = self.portfolio.id
        kwargs['max_size'] = sum(order.size for order in self.portfolio.orders_set.all() if order.stock == self.stock)
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        if self.is_sell:
            context['headline'] = "Create sell order for {} ({})".format(self.stock.symbol, self.stock.name)
        else:
            context['headline'] = "Create buy order"
        context['btn_txt'] = 'Create'
        return context

    def get_success_url(self):
        portfolio = self.object.portfolio.id
        return reverse_lazy('portfolio:portfolio_viewer', kwargs={'id': portfolio})

portfolio/views/portfolio_designer.py
import json
from datetime import timedelta

from dateutil import parser
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.db.models import Max
from django.views.decorators.http import require_POST

from portfolio.models import Portfolio, Orders
from stocks.models import Stock, Index, Region, Tag, Filter


@login_required(login_url='accounts:log_in')
def portfolio_designer(request):
    indices = Index.objects.select_related().all()
    regions = Region.objects.select_related().all()
    stocks = Stock.objects.select_related().all()
    latest_dates = Filter.objects.values('name', 'stock__symbol').filter(
        name__contains='LevermannScore').annotate(latest_created_at=Max("date"))
    filters = Filter.objects.select_related() \
        .filter(date__in=latest_dates.values('latest_created_at')) \
        .filter(name__contains='LevermannScore') \
        .order_by('-value')
    filter_data = {}
    for my_filter in filters:
        if my_filter.value in filter_data:
            filter_data[my_filter.value].append(my_filter.stock)
        else:
            filter_data[my_filter.value] = [my_filter.stock]
    tags = Tag.objects.select_related().filter(category='Industry').all()
    data = {
        'indices': indices,
        'regions': regions,
        'stocks': stocks,
        'tags': tags,
        'levermann': filter_data,
        'APPTITLE': 'Portfolio Designer'
    }
    return render(request, 'portfolio_designer.html', data)


@require_POST
@login_required(login_url='accounts:log_in')
def save_portfolio(request):
    user = get_object_or_404(User, pk=request.user.id)
    msg = ''
    if request.method == 'POST':
        name = request.POST.get('name')
        portfolio = request.POST.get('portfolio')
        if portfolio:
            portfolio = json.loads(portfolio)
        status, msg = __valid_portfolio(name, portfolio, user)
        if status:
            return __create_portfolio(name, portfolio, user)
    return HttpResponse(json.dumps({'message': "Couldn't create portfolio. {}".format(msg), 'status': 1}), status=200,
                        content_type='application/json')


def __create_portfolio(name, portfolio, user):
    portfolio_item = Portfolio(name=name, user=user, cash=0, initial_cash=0)
    order_items = []
    initial_cash = 0
    for items in portfolio:
        stock = Stock.objects.filter(id=items['id']).first()
        if not stock:
            return HttpResponse(json.dumps(
                {'message': "Stock {} doesnt exist.".format(items['id']), 'status': 1}),
                status=200,
                content_type='application/json')
        initial_cash += float(items['price']) * float(items['amount']) + float(items['commission'])
        myOrder = Orders(
            date=parser.parse(items['date'], ignoretz=True) + timedelta(days=1),
            size=int(items['amount']),
            price=float(items['price']),
            commission=float(items['commission']),
            stock_id=stock.id
        )
        order_items.append(myOrder)
    portfolio_item.initial_cash = initial_cash
    portfolio_item.save()
    for orderItem in order_items:
        orderItem.portfolio = portfolio_item
        orderItem.save()
    return HttpResponse(json.dumps({'message': "Created Portfolio {}".format(name), 'status': 0}),
                        content_type='application/json')


def __valid_portfolio(name, portfolio, user):
    if name:
        my_portfolio = Portfolio.objects.filter(name=name, user=user).first()
        if my_portfolio:
            return False, 'Portfolio already exists.'
    else:
        return False, 'Invalid portfolio name.'

    for item in portfolio:

        if not ('id' in item and 'price' in item and 'date' in item and 'amount' in item and 'commission' in item
                and item['amount'].isdigit() and is_number(item['price'])) \
                and item['id'].isdigit() and is_number(item['commission']):
            return False, 'Entry {} is wrong'.format(item)
    return True, ''


def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        return False

portfolio/templates/_modal.html
<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content"></div>
  </div>
</div>

portfolio/templates/delete.html
{% load widget_tweaks %}

{% load app_filters %}
{% if object.get_template_name in 'Orders,Portfolio,Dividend' %}
<form method="POST">
    {% csrf_token %}
    <div class="modal-body">
        <h1>Delete {{ object.get_template_name }}</h1>
        <p>Are you sure you want to delete {{ object.get_template_name }}:{{ object.id }}?</p>
    </div>

    <div class="modal-footer">
        <input type="submit" class="btn btn-danger" value="Confirm">
        <a href="{{ object.get_absolute_url }}" class='btn btn-primary'>Go back</a>
    </div>
</form>
{% else %}
<div class="alert alert-danger">
    <strong>Deletion</strong> of {{ object.get_template_name }} is not supported.
</div>
{% endif %}

portfolio/templates/portfolio_designer.html
{% extends 'layouts/default/base.html' %}

{% block content %}
{% load app_filters %}
<div class="mb-2 mt-2" id="msg"></div>
<div class="input-group mb-2 mr-sm-2">
  <div class="input-group-prepend">
    <div class="input-group-text">Name</div>
  </div>
  <input type="name" class="form-control" id="portfolioName" placeholder="ExamplePortfolio">
</div>
<div class="row">
  <div class="col-sm">
    <label>Stocks over index</label>
    <select class="selectpicker" id="overindex" data-header="Add stocks to your portfolio" data-live-search="true"
      multiple>
      {% for index in indices %}
      <optgroup label="{{ index.symbol }}">
        {% for stock in index.stocks.all %}
        <option data-subtext="{{ stock.name }}" value="{{ stock.id }}">{{ stock.symbol }}</option>
        {% endfor %}responseText
      </optgroup>
      {% endfor %}
    </select>
  </div>
  <div class="col-sm">
    <label>Stocks over region</label>
    <select class="selectpicker" id="overregion" data-header="Add stocks to your portfolio" data-live-search="true"
      multiple>
      {% for region in regions %}
      <optgroup label="{{ region.region }}">
        {% for stock in stocks.all %}
        {% if stock.region_id == region.id %}
        <option data-subtext="{{ stock.name }}" value="{{ stock.id }}">{{ stock.symbol }}</option>
        {% endif %}
        {% endfor %}
      </optgroup>
      {% endfor %}
    </select>
  </div>
  <div class="col-sm">
    <label>Stocks over industry</label>
    <select class="selectpicker" id="overindustry" data-header="Add stocks to your portfolio" data-live-search="true"
      multiple>
      {% for tag in tags %}
      <optgroup label="{{ tag.tag }}">
        {% for stock in tag.stocks.all %}
        <option data-subtext="{{ stock.name }}" value="{{ stock.id }}">{{ stock.symbol }}</option>
        {% endfor %}
      </optgroup>
      {% endfor %}
    </select>
  </div>
</div>
<div class="row">
  <div class="col-sm">
    <label>Levermann</label><br>
    <select class="selectpicker" id="overlevermann" data-header="Add stocks to your portfolio" data-live-search="true"
      multiple>
      {% for key, value in levermann.items %}
      <optgroup label="{{ key }}">
        {% for stock in value %}
        <option data-subtext="{{ stock.name }}" value="{{ stock.id }}">{{ stock.symbol }}</option>
        {% endfor %}responseText
      </optgroup>
      {% endfor %}
    </select>
  </div>
</div>
<table class="table table-striped table-dark mt-5" id="portfolio">
  <thead>
    <tr>
      <th scope="col">Symbol</th>
      <th scope="col">Amount</th>
      <th scope="col">Price per piece</th>
      <th scope="col">Commission</th>
      <th scope="col">Purchase Date</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>
<div class="charts">
  <div class="row">
    <div class="col-sm" id="stockChart"></div>
    <div class="col-sm" id="regionChart"></div>
    <div class="col-sm" id="industryChart"></div>
  </div>
</div>
<input type="button" class="btn btn-lg btn-block btn-dark" id="savePortfolio" name="savePortfolio" value="Save" />
<script>


  var gRegionData = PortFolioDesigner.createDataListBySelector('overregion');
  var gIndustryData = PortFolioDesigner.createDataListBySelector('overindustry');
  var gOrderDict = new Map();

  $('#overregion, #overindustry, #overindex, #overlevermann').change(function () {
    PortFolioDesigner.updateTable('#overregion, #overindustry, #overindex, #overlevermann', 'table tbody');
  });

  var chartDivStock = Highcharts.chart('stockChart', PortFolioDesigner.createChartOptions('Stocks'));
  var chartDivRegion = Highcharts.chart('regionChart', PortFolioDesigner.createChartOptions('Region'));
  var chartDivIndustry = Highcharts.chart('industryChart', PortFolioDesigner.createChartOptions('Industry'));

  function updateCharts(id) {
    if (PortFolioDesigner.orderComplete(gOrderDict, id)) {
      gOrderDict = PortFolioDesigner.updateOrderDict(gOrderDict);
      PortFolioDesigner.updateCharts([
        { 'chart': chartDivStock, 'data': PortFolioDesigner.getData(gOrderDict, false) },
        { 'chart': chartDivRegion, 'data': PortFolioDesigner.getDataCategory(gRegionData, gOrderDict) },
        { 'chart': chartDivIndustry, 'data': PortFolioDesigner.getDataCategory(gIndustryData, gOrderDict) }
      ])
    }
  }

  $(document).on('change', '.priceField, .amountField, .commissionField', function () {

    var id = $(this).attr("id");
    // get default values
    var stockId = PortFolioDesigner.getId(id);

    gOrderDict.set(stockId + '_COMMISSION', $(stockId + '_COMMISSION').val() ? $(stockId + '_COMMISSION').val() : "10.0");
    gOrderDict.set(stockId + '_DATE', $(stockId + '_DATE').val() ? $(stockId + '_DATE').val() : moment());
    gOrderDict.set(id, $(this).val().replace(',', '.'));
    PortFolioDesigner.printMap(gOrderDict);
    updateCharts(id);
  });


  $(document).on('change.datetimepicker', function (e) {
    if ('date' in e) {
      gOrderDict.set(e.target.id, e.date);
      PortFolioDesigner.printMap(gOrderDict);
      updateCharts(e.target.id);
    }
  });

  $('#savePortfolio').click(function () {
    $.ajax({
      type: "POST",
      url: "{% url 'portfolio:save_portfolio' %}",
      data: {
        'name': $('#portfolioName').val(),
        'csrfmiddlewaretoken': '{{ csrf_token }}',
        'portfolio': PortFolioDesigner.orderDictToJson(gOrderDict)
      },
      dataType: "json",
      success: function (response) {
        if(response.status == '0')
        {
          $("#msg").html('<div class="alert alert-success" role="alert">'+ response.message +'</div>');
        }
        else
        {
          $("#msg").html('<div class="alert alert-danger" role="alert">'+ response.message +'</div>');
        }
      },
      error: function (rs, e) {
        $("#msg").html('<div class="alert alert-danger" role="alert">'+ rs.responseText +'</div>');
      }
    });
  })

</script>

{% endblock %}

portfolio/templates/portfolio_list.html
{% extends 'layouts/default/base.html' %}
{% block content %}
{% include "_modal.html" %}
{% load app_filters %}
<h1>Portfolio</h1>
<div class="mb-5 panel-body table-responsive">
    <table id="sortable1" class="table" >
        <thead>
            <tr>
                <th>Name</th>
                <th>cash </th>
                <th>total value</th>
                <th/>
            </tr>
        </thead>
        <tbody>
        {% for portfolio in portfolios %}
        <tr>
            <td><a href="{% url 'portfolio:portfolio_viewer' id=portfolio.id %}">{{ portfolio.name }}</a></td>
            <td>{{ portfolio.cash }}</td>
            <td>{{ portfolio.cash }}</td>
            <td><button class="btn btn-danger" id="delete{{ portfolio.id }}"><i class="fa fa-trash"></i></button></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script>
$(document).ready(function()
{
    {% for portfolio in portfolios %}
    $("#delete{{ portfolio.id }}").modalForm({
        formURL: "{% url 'portfolio:portfolio_delete_view' pk=portfolio.id%}"
    });
    {% endfor %}

});

</script>
{% endblock %}

portfolio/templates/post.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">{{ headline }}</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">{{ btn_txt }}</button>
  </div>
</form>