app/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from main.views import IndexPageView

urlpatterns = [
    url('i18n/', include('django.conf.urls.i18n')),
    url(r'^stocks/', include('stocks.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexPageView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        url(r'__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

stocks/urls.py
from django.conf.urls import url

from stocks.views import strategy, orders
from stocks.views import misc

app_name = 'stocks'

urlpatterns = [
    url(r'^index[/]*$', misc.stock_list_index, name='stock_list_index'),
    url(r'^region[/]*$', misc.stock_list_region, name='stock_list_region'),
    url(r'^signals[/]*$', misc.stock_signal, name='stock_signal'),
    url(r'^signal/view/(?P<signal_id>\d+)[/]*$',
        misc.stock_signal_viewer_id, name='stock_signal_viewer_id'),
    url(r'^portfolio/(?P<id>\w+)[/]*$',
        strategy.strategy_viewer, name='portfolio_viewer'),
    url(r'^signals/performance[/]*$', misc.stock_signal_performance,
        name='stock_signal_performance'),
    url(r'^signals/today[/]*$', misc.stock_signal_today,
        name='stock_signal_today'),
    url(r'^(?P<stock_id>[\d]+)[/]*$', misc.stock_data, name='stock_data'),
    url(r'^filter/stock_is_hot[/]*$', misc.stock_list_filter_stock_is_hot,
        name='stock_list_filter_stock_is_hot'),
    url(r'^filter/piotroski[/]*$', misc.stock_list_filter_piotroski,
        name='stock_list_filter_piotroski'),
    url(r'^filter/levermann[/]*$', misc.stock_list_filter_levermann,
        name='stock_list_filter_levermann'),
    url(r'^filter[/]*$', misc.stock_list_filter,
        name='stock_list_filter'),
    url(r'^strategies[/]*$', strategy.strategy_list, name='strategies'),
    url(r'^strategy/view/(?P<id>\w+)[/]*$', strategy.strategy_viewer, name='strategy_view'),
    url(r'^order/view/(?P<order_id>\d+)[/]*$',
        misc.order_view, name='order_viewer_id'),
    url(r'^order/delete/(?P<pk>\d+)/', orders.OrderDeleteView.as_view(), name='order_delete_view'),
    url(r'^order/add/', orders.OrderCreateView.as_view(), name='order_create_view'),
    url(r'^strategy/delete/(?P<pk>\d+)/', strategy.StrategyDeleteView.as_view(), name='strategy_delete_view'),
]

stocks/forms/order_form.py
import uuid

from django.forms import ModelForm, DateTimeField
from tempus_dominus.widgets import DateTimePicker

from stocks.models import Orders


class OrdersForm(ModelForm):
    date = DateTimeField(
        widget=DateTimePicker(
            options={
                'useCurrent': True,
                'collapse': False,
            },
            attrs={
                'append': 'fa fa-calendar',
                'icon_toggle': True,
            }
        ),
    )

    def __init__(self, *args, **kwargs):
        super(OrdersForm, self).__init__(*args, **kwargs)
        self.fields['price'].required = True
        self.fields['commission'].required = True

    class Meta:
        model = Orders
        fields = ['stock', 'portfolio', 'size', 'price',  'commission', 'date']

    def save(self, commit=True):
        my_order = super(OrdersForm, self).save(commit=False)
        data = self.cleaned_data
        my_order.status = 'completed'
        my_order.order_type = 'market'
        my_order.order_uuid = uuid.uuid4()
        my_order.price_complete = float(data['price']) * float(data['size'])
        my_order.is_sell = False
        if commit:
            my_order.save()
        return my_order

portfolio/views/orders.py
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalDeleteView
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse

from portfolio.forms.order_form import OrderForm
from portfolio.forms.order_form_update import OrderFormUpdate
from portfolio.models import Portfolio, Orders

from stocks.models import Stock


class OrderDeleteView(BSModalDeleteView):
    model = Orders
    fields = '__all__'
    success_message = 'Success: Order was deleted.'
    template_name = 'delete.html'

    def get_success_url(self):
        portfolio = self.object.portfolio.id
        return reverse_lazy('portfolio:portfolio_viewer', kwargs={'id': portfolio})


class OrderUpdateView(BSModalUpdateView):
    template_name = 'post.html'
    form_class = OrderFormUpdate
    success_message = 'Success: Order was updated.'
    order = None
    portfolio = None
    model = Orders

    def dispatch(self, request, *args, **kwargs):
        self.order = get_object_or_404(Orders, id=kwargs['pk'])
        self.portfolio = get_object_or_404(Portfolio, id=self.order.portfolio_id, user=request.user)
        return super(OrderUpdateView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(OrderUpdateView, self).get_context_data(**kwargs)
        context['headline'] = 'Update order {}'.format(self.order.id)
        context['btn_txt'] = 'Save'
        return context


class OrderCreateView(BSModalCreateView):
    portfolio = None
    stock = None
    is_sell = True
    template_name = 'post.html'
    form_class = OrderForm

    def dispatch(self, request, *args, **kwargs):
        self.portfolio = get_object_or_404(Portfolio, id=kwargs['portfolio_id'], user=request.user)
        self.is_sell = '/sell/' in request.path
        self.stock = None
        if self.is_sell:
            self.stock = get_object_or_404(Stock, id=kwargs['stock_id'])
        return super(OrderCreateView, self).dispatch(request, *args, **kwargs)

    def get_form_kwargs(self):
        kwargs = super(OrderCreateView, self).get_form_kwargs()
        kwargs['sell'] = self.is_sell
        kwargs['stock_id'] = None if self.stock is None else self.stock.id
        kwargs['portfolio_id'] = self.portfolio.id
        kwargs['max_size'] = sum(order.size for order in self.portfolio.orders_set.all() if order.stock == self.stock)
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(OrderCreateView, self).get_context_data(**kwargs)
        if self.is_sell:
            context['headline'] = "Create sell order for {} ({})".format(self.stock.symbol, self.stock.name)
        else:
            context['headline'] = "Create buy order"
        context['btn_txt'] = 'Create'
        return context

    def get_success_url(self):
        portfolio = self.object.portfolio.id
        return reverse_lazy('portfolio:portfolio_viewer', kwargs={'id': portfolio})

stocks/views/misc.py
import base64
import json
import zlib

from json2html import *
from datetime import date, datetime, timedelta

from django.db.models import Avg, Count,Max
from django.shortcuts import render
from stocks.models import Filter, Jsondata, Orders, Parameter, \
    Plot, Series, Signal, Stock, Index, Region
from stocks.tools.json import json_serial


def create_filter_date_range():
    date_last = Filter.objects.latest('date').date
    date_range = (
        # The start_date with the minimum possible time
        datetime.combine(date_last, datetime.min.time()),
        # The start_date with the maximum possible time
        datetime.combine(date_last, datetime.max.time())
    )
    return date_range


def order_view(request, order_id):
    data = {
        "order": Orders.objects.filter(id=order_id).first()
    }
    return render(request, 'order.html', data)


def stock_signal(request):
    signals = list(Signal.objects.values('stock__symbol', 'stock__id', 'id',
                                         'name', 'profit_in_percent', 'status'))
    signal_pivot = {}
    for signal in signals:
        signal_pivot.setdefault(signal['stock__id'], {}).update(
            {'%s' % signal['name']: [signal['stock__id'], signal['profit_in_percent'],
                                     signal['status'], signal['stock__symbol'], signal['id']]})
    data = {
        'signals': signal_pivot,
        'titles': list(Signal.objects.values_list('name', flat=True).distinct()),
        'APPTITLE': 'Signal Performance'
    }
    return render(request, 'stock_signal.html', data)


def __create_overall_performance(signals):
    overall_performance = []
    for signal in signals:
        overall_performance.append([signal['name'], signal['total']])
    return json.dumps(overall_performance)


def __create_performance_over_indices(signals_index):
    json_container = []
    categories = []
    index_before = ""
    for signal in signals_index:
        if index_before == "" or index_before != signal['stock__index__symbol']:
            index_before = signal['stock__index__symbol']
            json_container.append({"name": index_before, "data": []})
        if index_before == signal['stock__index__symbol']:
            json_container[len(json_container) - 1]['name'] = signal['stock__index__symbol']
            json_container[len(json_container) - 1]['data'].append(signal['total'])
        if signal['name'] not in categories:
            categories.append(signal['name'])
    return json.dumps(categories), json.dumps(json_container)


def stock_signal_performance(request):
    signals_index = list(Signal.objects.values('name', 'stock__index__symbol').annotate(
        total=Avg('profit_in_percent')).order_by('stock__index__symbol', 'name'))
    signals = list(Signal.objects.values('name').annotate(total=Avg('profit_in_percent')).
                   order_by('name'))
    categories, json_container = __create_performance_over_indices(signals_index)
    data = {
        'categories': categories,
        'signals_index': json_container,
        'signals': __create_overall_performance(signals),
        'APPTITLE': 'Signal Performance'
    }
    return render(request, 'stock_signal_performance.html', data)


def stock_list_index(request):
    indices = Index.objects.select_related().all()
    data = {
        'indices': indices,
        'APPTITLE': 'Stock List'
    }
    return render(request, 'stock_list_index.html', data)


def stock_list_region(request):
    regions = Region.objects.select_related().all()
    stocks = Stock.objects.select_related().all()
    data = {
        'regions': regions,
        'stocks': stocks,
        'APPTITLE': 'Stock List over region'
    }
    return render(request, 'stock_list_region.html', data)


def stock_list_filter(request):
    latest_dates = Filter.objects.values('name', 'stock__symbol').annotate(latest_created_at=Max("date"))
    filters = Filter.objects.values('name', 'stock__symbol', 'stock__id', 'status', 'value')\
        .filter(date__in=latest_dates.values('latest_created_at')).order_by('stock__symbol', 'name')
    filter_names = list(Filter.objects.values('name').annotate(Count('name')).order_by('name'))
    data = {
        'header': [value['name'] for value in filter_names],
        'filters': list(filters.all()),
        'APPTITLE': 'Filter'
    }
    return render(request, 'filter.html', data)


def stock_list_filter_stock_is_hot(request):
    latest_dates = Filter.objects.values('name', 'stock__symbol').filter(name__contains='StockIsHot').annotate(latest_created_at=Max("date"))
    filters = Filter.objects.values('name', 'stock__symbol', 'stock__id','status', 'value') \
        .filter(date__in=latest_dates.values('latest_created_at')) \
        .filter(name__contains='StockIsHot') \
        .order_by('stock__symbol', 'name')
    data = {
        'header': ['StockIsHot2', 'StockIsHot3', 'StockIsHot6'],
        'filters': filters
    }
    return render(request, 'filter.html', data)


def stock_list_filter_piotroski(request):
    latest_dates = Filter.objects.values('name', 'stock__symbol').filter(name__contains='PiotroskiScore').annotate(latest_created_at=Max("date"))
    filters = Filter.objects.values('name', 'stock__symbol', 'stock__id','status', 'value') \
        .filter(date__in=latest_dates.values('latest_created_at')) \
        .filter(name__contains='PiotroskiScore') \
        .order_by('stock__symbol', 'name')
    data = {
        'header': ['Piotroski'],
        'filters': filters
    }

    return render(request, 'filter.html', data)


def stock_list_filter_levermann(request):
    latest_dates = Filter.objects.values('name', 'stock__symbol').filter(name__contains='LevermannScore').annotate(latest_created_at=Max("date"))
    filters = Filter.objects.values('name', 'stock__symbol', 'stock__id', 'status', 'value') \
        .filter(date__in=latest_dates.values('latest_created_at')) \
        .filter(name__contains='LevermannScore') \
        .order_by('stock__symbol', 'name')
    data = {
        'header': ['Levermann'],
        'filters': filters
    }

    return render(request, 'filter.html', data)


def prettify_json_data(json_data):
    item_list = []
    for data in json_data:
        item_list.append(
            {
                "name": data.name,
                "data": json2html.convert(json=json.loads(data.data), table_attributes="class=\"table\"")
            }
        )
    return item_list


def stock_data(request, stock_id):
    stock = Stock.objects.select_related().filter(id=stock_id)[0]
    plot_data = list(Series.objects.values_list('date', 'priceclose').filter(resolution='P1D').filter(stock__id=stock_id).order_by('date'))
    filter_data = Filter.objects.filter(stock__id=stock_id).order_by('date')
    json_data = Jsondata.objects.filter(stock__id=stock_id)
    signal_data = Signal.objects.select_related().filter(stock__id=stock_id).order_by('date')
    signal_plot_data = {}
    status = {
        -2: "strong sell",
        -1: "sell",
        0: "hold",
        1: "buy",
        2: "strong buy",
    }
    for my_signal in signal_data:
        if my_signal.name not in signal_plot_data:
            signal_plot_data[my_signal.name] = {
                'name': my_signal.name,
                'data': []
            }
        signal_plot_data[my_signal.name]['data'].append({
            "x": my_signal.date.date(),
            "y": my_signal.profit_in_percent,
            "status": status[my_signal.status],
            "parameter": ", ".join(str(param.value) for param in my_signal.parameter_set.all())
        })
    filter_plot_data = {}
    for my_filter in filter_data:
        if my_filter.name not in filter_plot_data:
            filter_plot_data[my_filter.name] = {
                'name': my_filter.name,
                'data': []
            }
        filter_plot_data[my_filter.name]['data'].append({
            "x": my_filter.date.date(),
            "y": my_filter.value,
            "status": "buy" if my_filter.status == 1 else "sell"
            })
    series_lines = []
    series_signal = []
    for plot_key in filter_plot_data:
        series_lines.append({
            'name': filter_plot_data[plot_key]['name'],
            'data': filter_plot_data[plot_key]['data']
        })
    for plot_key in signal_plot_data:
        series_signal.append({
            'name': signal_plot_data[plot_key]['name'],
            'data': signal_plot_data[plot_key]['data']
        })
    data = {
        'stock': stock,
        'data':  json.dumps(plot_data, default=json_serial),
        'filters_da': json.dumps(series_lines, default=json_serial),
        'signals_da': json.dumps(series_signal, default=json_serial),
        'jsondata': prettify_json_data(list(json_data))
    }
    return render(request, 'stock_data.html', data)


def stock_signal_viewer(request, stock_id, signal):
    stock = Stock.objects.filter(id=stock_id)[0]
    signal_data = Signal.objects.filter(stock__id=stock_id, name=signal).order_by('-date').first()
    plot_data = Plot.objects.values_list('data').filter(signal__id=signal_data.id).first()
    # converts binary blob to json
    plot_data = get_json_plot(plot_data)

    parameters = Parameter.objects.values_list('value').filter(signal__id=signal_data.id).all()
    data = {
        'stock': stock,
        'title': signal_data.name + "({0})".format(", ".join(str(x[0]) for x in parameters)),
        'subtitle': "Calculated on:" + signal_data.date.isoformat(),
        'data': plot_data
    }

    return render(request, 'stock_signal_viewer.html', data)


def get_json_plot(plot_data):
    import binascii
    try:
        json_plot = zlib.decompress(base64.b64decode(plot_data[0])).decode('utf-8')
        return json_plot
    except binascii.Error:
        return [{}, {}, {}, {}]


def stock_signal_viewer_id(request, signal_id):
    signal_data = Signal.objects.filter(id=signal_id).first()
    stock = Stock.objects.filter(id=signal_data.stock_id).first()

stocks/views/orders.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView, CreateView

from stocks.forms.order_form import OrdersForm
from stocks.models import Orders


class OrderDeleteView(DeleteView):
    model = Orders
    fields = '__all__'
    template_name = 'delete.html'

    def get_success_url(self):
        portfolio = self.object.portfolio.id
        return reverse_lazy('stocks:strategy_view', kwargs={'id': portfolio})


class OrderCreateView(CreateView):
    object = None
    template_name = 'order_create.html'
    form_class = OrdersForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

stocks/templates/delete_view.html
{% extends 'layouts/default/delete_view.html' %}

stocks/templates/filter.html
{% extends 'layouts/default/base.html' %}

{% block content %}
<h1>Score list</h1>
<table id="sortable_filter" class="table" >
    <thead>
        <tr>
            <th class="sortable">Symbol <i class="fa fa-fw fa-sort"></i></th>
            {% for title in header %}
            <th class="sortable">{{ title }} <i class="fa fa-fw fa-sort"></i></th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% with ctx=header|length%}
    {% for filter in filters %}
    {% if forloop.counter0|divisibleby:ctx %}
    <tr>
    <td><a href="{% url 'stocks:stock_data' stock_id=filter.stock__id %}">{{ filter.stock__symbol }}</a></td>
    {% endif %}
    {% if filter.status == 0 %}
        <td class="alert alert-danger">{{ filter.value }}</td>
    {% endif %}
    {% if filter.status == 1 %}
        <td class="alert alert-success">{{ filter.value }}</td>
    {% endif %}
    {% if filter.status == 2 %}
        <td class="alert alert-warning">{{ filter.value }}</td>
    {% endif %}
    {% if forloop.counter|divisibleby:ctx %}
    </tr>
    {% endif %}
    {% endfor %}
    {% endwith %}
    </tbody>
</table>

<script>
$(function(){
  $("#sortable_filter").tablesorter();
});
</script>

{% endblock %}

stocks/templates/stock_list_index.html
{% extends 'layouts/default/base.html' %}

{% block content %}
<h1>Stocks</h1>

<ul class="list-group">
    {% for index in indices %}
    <h2>{{ index.symbol }}</h2>
    {% for stock in index.stocks.all %}
    <li class="list-group-item"><a href="{% url 'stocks:stock_data' stock_id=stock.id %}">{{ stock.symbol }}</a></li>
    {% endfor %}
    {% endfor %}
</ul>
{% endblock %}

stocks/templates/stock_signal.html
{% extends 'layouts/default/base.html' %}

{% block content %}
{% load app_filters %}
<h1>Signals</h1>
<table id="sortable1" class="table" >
    <thead>
        <tr>
            <th class="sortable">Symbol<i class="fa fa-fw fa-sort"></i></th>
            {% for title in titles %}
            <th class="sortable">{{ title }} <i class="fa fa-fw fa-sort"></i></th>
            {% endfor %}
        </tr>
    </thead>
    <tbody>
    {% for stock , signal in signals.items %}
    <tr>
        {% for title in titles %}
        {% for key, value in signal.items %}
        {% if key == title %}
        {% if forloop.counter0 == 0 %}
        <td><a href="{% url 'stocks:stock_data' stock_id=value.0 %}">{{ value.3 }}</a></td>
        {% endif %}
        {% if value.2 == -2 %}

        <td class="alert alert-danger"><a href="{% url 'stocks:stock_signal_viewer_id' signal_id=value.4 %}">{{ value.1 }}</a></td>
        {% elif value.2  == 2 %}
        <td class="alert alert-success"><a href="{% url 'stocks:stock_signal_viewer_id' signal_id=value.4 %}">{{ value.1 }}</a></td>
        {% elif value.2  == 1 %}
        <td class="alert alert-info"><a href="{% url 'stocks:stock_signal_viewer_id' signal_id=value.4 %}">{{ value.1 }}</a></td>
        {% else %}
        <td class="alert alert-warning"><a href="{% url 'stocks:stock_signal_viewer_id' signal_id=value.4 %}">{{ value.1 }}</a></td>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% endfor %}
    </tr>
    {% endfor %}
    </tbody>
</table>

<script>
$(function () {
    // sortable tables
    $("#sortable1").tablesorter();
});
</script>
{% endblock %}

stocks/templates/strategy.html
{% extends 'layouts/default/base.html' %}

{% block content %}
{% load app_filters %}
<h1>Portfolio {{ portfolioname }}</h1>
<h2>Diversification</h2>
<div class="charts">
  <div class="row">
    <div class="col-sm" id="stockChart"></div>
    <div class="col-sm" id="regionChart"></div>
    <div class="col-sm" id="industryChart"></div>
  </div>
</div>
{% if portfolio_graph|length > 0 %}
<div class="mb-5" id="chart" style="width:100%; height:600px;"></div>
{% endif %}
{% if signal_stats|length > 0 %}
<h2>Signal performance</h2>
<div class="mb-5" id="chartPerformance" style="width:100%; height:600px;"></div>
{% endif %}
{% for item in performance %}
<h2>{{ item.name }} performance</h2>
<div class="mb-5 panel-body table-responsive">
    <table id="sortable{{ item.name }}" class="table" >
        <thead>
            <tr>
                <th class="sortable">Stock <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Earnings <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Levermann <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Piotroski <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Date <i class="fa fa-fw fa-sort"></i></th>
                <th/>
            </tr>
        </thead>
        <tbody>
        {% for sub in item.data %}
        <tr>
            <td><a href="{% url 'stocks:stock_data' stock_id=sub.stock__id %}">{{ sub.stock__symbol }} ({{ sub.stock__name }})</a></td>
            {% if sub.earnings < 0.0 %}
            <td class="alert alert-danger">{{ sub.earnings|floatformat:2 }}</td>
            {% else %}
            <td class="alert alert-success">{{ sub.earnings|floatformat:2 }}</td>
            {% endif %}

            {% if  sub.levermann_status == 0 %}
            <td class="alert alert-danger">{{ sub.levermann }}</td>
            {% elif  sub.levermann_status == 1 %}
            <td class="alert alert-success">{{ sub.levermann }}</td>
            {% elif  sub.levermann_status == 2 %}
            <td class="alert alert-warning">{{ sub.levermann }}</td>
            {% else %}
            <td>{{ sub.levermann }}</td>
            {% endif %}

            {% if sub.piotroski_status == 0 %}
            <td class="alert alert-danger">{{ sub.piotroski }}</td>
            {% elif  sub.piotroski_status == 1 %}
            <td class="alert alert-success">{{ sub.piotroski }}</td>
            {% elif  sub.piotroski_status == 2 %}
            <td class="alert alert-warning">{{ sub.piotroski }}</td>
            {% else %}
            <td>{{ sub.piotroski }}</td>
            {% endif %}
            <td>{{ sub.date }}</td>
            <td><button class="btn" id="{{ sub.stock__id }}"><i class="fa fa-dollar"></i></button></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script>
$(function(){
  $("#sortable{{ item.name }}").tablesorter();
});
</script>
{% endfor %}
{% for title in titles %}
<h2>{{ title.name }}</h2>
<div class="mb-5 panel-body table-responsive">
    <table id="sortable{{ forloop.counter }}" class="table" >
        <thead>
            <tr>
                <th class="sortable">Stock <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Type <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">price <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">commission <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Size <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Price complete <i class="fa fa-fw fa-sort"></i></th>
                <th>Status</th>
                <th class="sortable">Date <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Signal <i class="fa fa-fw fa-sort"></i></th>
                <th class="sortable">Order <i class="fa fa-fw fa-sort"></i></th>
                <th/>
            </tr>
        </thead>
        <tbody>
        {% for order in title.data %}
        <tr>
            <td><a href="{% url 'stocks:stock_data' stock_id=order.stock.id %}">{{ order.stock.symbol }} ({{ order.stock.name }})</a></td>
            <td>{{ order.order_type }}</td>
            <td>{{ order.price }}</td>
            <td>{{ order.commission }}</td>
            <td>{{ order.size }}</td>
            <td>{{ order.price_complete }}</td>
            <td>{{ order.status }}</td>
            <td>{{ order.date }}</td>
            {% if order.signal.id  %}
            <td><a href="{% url 'stocks:stock_signal_viewer_id' signal_id=order.signal.id  %}">{{ order.signal.name }}</a></td>
            {% else %}
             <td></td>
            {% endif %}
            <td><a href="{% url 'stocks:order_viewer_id' order_id=order.id  %}">{{ order.id }}</a></td>
            <td> <a href="{{ order.get_delete_url }}" class="btn btn-danger"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<script>
$(function(){
  $("#sortable{{ forloop.counter }}").tablesorter();
});
</script>
{% endfor %}

<script>


$(function () {
    var chartDivStock = Highcharts.chart('stockChart', PortFolioDesigner.createChartOptionsData('Stocks', {{ stocks_data|safe }}));
    var chartDivRegion = Highcharts.chart('regionChart', PortFolioDesigner.createChartOptionsData('Region', {{ regions_data|safe }}));
    var chartDivIndustry = Highcharts.chart('industryChart', PortFolioDesigner.createChartOptionsData('Industry', {{ industry_data|safe }}));
 {% if  signal_stats|length > 0 %}
    Highcharts.chart('chartPerformance', {
        chart: {
            type: 'bar'
        },
        title: {
            text: ''
        },
        xAxis: {
            type: 'category',
        },
        yAxis: {
            title: {
                text: 'Earnings in €'
            }
        },
        credits: {
            enabled: false
        },
        series:  [{
            name: 'Signal performance',
            data: {{ signal_stats|safe }}
        }]
    });
{% endif %}
{% if  portfolio_graph|length > 0 %}

    Highcharts.chart('chart', {
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            type: 'datetime'
        },
        yAxis: {
            title: {
                text: 'Portfolio cash in €'
            }
        },
        credits: {
            enabled: false
        },
        series:  [{
            name: 'Overall performance',
            data: {{ portfolio_graph }}
        }]
    });
{% endif %}
});
</script>
{% endblock %}