accounts/urls.py
from django.conf.urls import url
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView,
)

app_name = 'accounts'

urlpatterns = [
    url('log-in/', LogInView.as_view(), name='log_in'),
    url('log-out/', LogOutView.as_view(), name='log_out'),

    url('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    url('sign-up/', SignUpView.as_view(), name='sign_up'),
    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    url('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    url('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    url('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    url('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    url('change/password/', ChangePasswordView.as_view(), name='change_password'),
    url('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

app/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin
from django.conf.urls.static import static

from main.views import IndexPageView

urlpatterns = [
    url('i18n/', include('django.conf.urls.i18n')),
    url(r'^stocks/', include('stocks.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^portfolio/', include('portfolio.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexPageView.as_view(), name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns = [
        url(r'__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

portfolio/urls.py
from django.conf.urls import url

from portfolio.views import portfolio_designer, portfolio, orders, dividend


app_name = 'portfolio'

urlpatterns = [
    url(r'^view/(?P<id>\d+)[/]*$', portfolio.portfolio_viewer, name='portfolio_viewer'),
    url(r'^list[/]*$', portfolio.portfolio_list, name='portfolio_list'),
    url(r'^designer[/]*$', portfolio_designer.portfolio_designer, name='portfolio_designer'),
    url(r'^save/', portfolio_designer.save_portfolio, name='save_portfolio'),
    url(r'^order/delete/(?P<pk>\d+)/', orders.OrderDeleteView.as_view(), name='order_delete_view'),
    url(r'^order/add/', orders.OrderCreateView.as_view(), name='order_create_view'),
    url(r'^order/buy/(?P<portfolio_id>\d+)/', orders.OrderCreateView.as_view(), name='buy'),
    url(r'^order/sell/(?P<portfolio_id>\d+)/(?P<stock_id>\d+)/', orders.OrderCreateView.as_view(), name='sell'),
    url(r'^dividend/add/(?P<portfolio_id>\d+)/(?P<stock_id>\d+)/', dividend.DividendCreateView.as_view(), name='dividend'),
    url(r'^dividend/edit/(?P<pk>\d+)/', dividend.DividendEditView.as_view(), name='div_edit'),
    url(r'^dividend/delete/(?P<pk>\d+)/', dividend.DividendDeleteView.as_view(), name='div_delete'),
    url(r'^order/edit/(?P<pk>\d+)/', orders.OrderUpdateView.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)/', portfolio.PortfolioDeleteView.as_view(), name='portfolio_delete_view')
]

stocks/urls.py
from django.conf.urls import url

from stocks.views import strategy, orders
from stocks.views import misc

app_name = 'stocks'

urlpatterns = [
    url(r'^index[/]*$', misc.stock_list_index, name='stock_list_index'),
    url(r'^region[/]*$', misc.stock_list_region, name='stock_list_region'),
    url(r'^signals[/]*$', misc.stock_signal, name='stock_signal'),
    url(r'^signal/view/(?P<signal_id>\d+)[/]*$',
        misc.stock_signal_viewer_id, name='stock_signal_viewer_id'),
    url(r'^portfolio/(?P<id>\w+)[/]*$',
        strategy.strategy_viewer, name='portfolio_viewer'),
    url(r'^signals/performance[/]*$', misc.stock_signal_performance,
        name='stock_signal_performance'),
    url(r'^signals/today[/]*$', misc.stock_signal_today,
        name='stock_signal_today'),
    url(r'^(?P<stock_id>[\d]+)[/]*$', misc.stock_data, name='stock_data'),
    url(r'^filter/stock_is_hot[/]*$', misc.stock_list_filter_stock_is_hot,
        name='stock_list_filter_stock_is_hot'),
    url(r'^filter/piotroski[/]*$', misc.stock_list_filter_piotroski,
        name='stock_list_filter_piotroski'),
    url(r'^filter/levermann[/]*$', misc.stock_list_filter_levermann,
        name='stock_list_filter_levermann'),
    url(r'^filter[/]*$', misc.stock_list_filter,
        name='stock_list_filter'),
    url(r'^strategies[/]*$', strategy.strategy_list, name='strategies'),
    url(r'^strategy/view/(?P<id>\w+)[/]*$', strategy.strategy_viewer, name='strategy_view'),
    url(r'^order/view/(?P<order_id>\d+)[/]*$',
        misc.order_view, name='order_viewer_id'),
    url(r'^order/delete/(?P<pk>\d+)/', orders.OrderDeleteView.as_view(), name='order_delete_view'),
    url(r'^order/add/', orders.OrderCreateView.as_view(), name='order_create_view'),
    url(r'^strategy/delete/(?P<pk>\d+)/', strategy.StrategyDeleteView.as_view(), name='strategy_delete_view'),
]

content/templates/layouts/default/base.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0 minimal-ui"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    {% load static %}
    <title>{{ APPTITLE }}</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}"/>
    <link href="{% static 'app.css' %}" rel="stylesheet">
    <script src="{% static 'app.js' %}"></script>
    {% block head %}{% endblock %}
</head>
<body>
<!-- Messages -->
<div>
    {% if messages %}
    {% for message in messages %}
    <div style="border-radius:0;" {% if message.tags %}
         class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
</div>
<!-- End Messages -->
<nav class="navbar navbar-expand-sm navbar-light bg-faded">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content"
            aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="#">AutoTrader</a>
    <div class="collapse navbar-collapse" id="nav-content">
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="SignalPrev1" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">Stocks</a>
                <div class="dropdown-menu" aria-labelledby="Preview">
                    <a class="dropdown-item" href="{% url 'stocks:stock_list_index' %}">Over index</a>
                    <a class="dropdown-item" href="{% url 'stocks:stock_list_region' %}">Over region</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="SignalPrev" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">Signals</a>
                <div class="dropdown-menu" aria-labelledby="Preview">
                    <a class="dropdown-item" href="{% url 'stocks:stock_signal' %}">Overview</a>
                    <a class="dropdown-item" href="{% url 'stocks:stock_signal_performance' %}">Performance</a>
                    <a class="dropdown-item" href="{% url 'stocks:stock_signal_today' %}">Today</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="Preview" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">Filter</a>
                <div class="dropdown-menu" aria-labelledby="Preview">
                    <a class="dropdown-item" href="{% url 'stocks:stock_list_filter_stock_is_hot' %}">StockIsHot</a>
                    <a class="dropdown-item" href="{% url 'stocks:stock_list_filter_piotroski' %}">Piotroski</a>
                    <a class="dropdown-item" href="{% url 'stocks:stock_list_filter_levermann' %}">Levermann</a>
                    <a class="dropdown-item" href="{% url 'stocks:stock_list_filter' %}">All</a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'stocks:strategies' %}">Strategies</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="MyPortfolios" href="#" role="button"
                   aria-haspopup="true" aria-expanded="false">Portfolio Manager</a>
                <div class="dropdown-menu" aria-labelledby="MyPortfolios">
                    <a class="nav-link" href="{% url 'portfolio:portfolio_designer' %}">Add Portfolio</a>
                    <a class="nav-link" href="{% url 'portfolio:portfolio_list' %}">My Portfolios</a>
                </div>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:log_out' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item ml-5 mr-2">
                <a class="btn btn-success" href="{% url 'accounts:sign_up' %}">Signup</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-primary" href="{% url 'accounts:log_in' %}">login</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container">
    <div id="banner" class="page-header">
        <h1>{% block title %}{{ APPTITLE }}{% endblock %}</h1>
    </div>
    {% block content %}{% endblock %}
</div>
</body>
</html>